# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'HowTalk' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for HowTalk
pod 'SnapKit', '~> 5.0.0'
pod 'Firebase/Core'
pod 'Firebase/RemoteConfig'
pod 'TextFieldEffects'
pod 'Firebase/Database'
pod 'Firebase/Auth'
pod 'Firebase/Storage'
pod 'ObjectMapper', '~> 3.5'

end
